backend:
  name: github
  repo: markmcsweeny95-debug/7th-worcester-scouts
  branch: main
  auth_type: implicit

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
